### ISSUE TITLE
todo bot issue opened with his keywords

### ISSUE THREAD

**Issue by Seluj78** [JasonEtco/todo#101]
https://github.com/Seluj78/42PyChecker/issues/82
https://github.com/Seluj78/42PyChecker/issues/83

**Comment by Seluj78** [comment]
I think what caused it is the fact that the config.yml file isn't blacklisted

**Comment by Seluj78** [comment]
or me naming it `.config.yml` instead of `config.yml`

**Comment by JasonEtco** [comment]
> or me naming it .config.yml instead of config.yml

That would do it. `.github/config.yml` is blacklisted.
