### ISSUE TITLE
look for TODO comments in diffs only

### ISSUE THREAD

**Issue by gr2m** [JasonEtco/todo#102]
See https://github.com/gr2m/octokit-rest-browser-experimental/pull/19

The TODO app commented on the PR although the TODO comments have been there before, I'd expect the TODO app not to react on these but only TODO comments added or changed in the PR itself

**Comment by JasonEtco** [comment]
This is a great idea. I'm refactoring the core internals right now, and this should come after. Noting for posterity:

You can get the diff of a PR:

```
curl https://patch-diff.githubusercontent.com/raw/gr2m/octokit-rest-browser-experimental/pull/19.diff
```

A quick RegEx to match keywords, file names and titles in diffs:

```
/diff --git a\/.+ b\/(.+)[\s\S]+[+\-].*(@todo|TODO )(?:[:-\s]+)?(.*)[\s\S]+diff --git /gm
```
