### ISSUE TITLE
Unable to generate new issues [python]

### ISSUE THREAD

**Issue by jaumebonet** [JasonEtco/todo#105]
Hi,

I've started trying the app, as I think is a fantastic idea. 

For some reason, it does not seem to do anything in the repo I expect it to track. As you can see in this commit https://github.com/jaumebonet/RosettaSilentToolbox/pull/6/commits/b440ddf02831430c27c226e0ebe9a4fe3f389623, I've added a couple of todos (this commit and its parent) but I cannot get it to create the corresponding issues. 
I'm guessing I'm missing something, but I cannot see what it is.

The only thing I can think about is that the master branch of this repo is **protected** so that merges need to be approved. I don't know if this might have something to do(?).

Thanks!
J.-

**Comment by JasonEtco** [comment]
Hey @jaumebonet! The app is down right now for some deployment issues :( I'll go ahead and close this issue when its back up.

**Comment by jaumebonet** [comment]
@JasonEtco,
It happens! :)
Thanks for your reply!

**Comment by JasonEtco** [comment]
@jaumebonet it should be all sorted now. FYI, when the commits are in a PR it'll comment on the PR instead of opening a new issue; when you merge that PR, it'll open issues for the remaining TODOs. To get it synced up, just push to your PR 👍
