### ISSUE TITLE
Allow Markdown in @body

### ISSUE THREAD

**Issue by Rayraegah** [JasonEtco/todo#107]
If/when you make @body multi-line would be nice to have `contents` of @body parsed as markdown. This helps add useful things like links, checklists, maybe even relate to other todos.

**Comment by JasonEtco** [comment]
@Rayraegah This should already work.

If you were to push:

```js
/**
  * @todo Hello
  * @body This is **bold**, this is *italic*
  */
```

The **bold** and *italic* text should render properly in GitHub.

I'm going to close this, but let me know if it doesn't work and I can look into it 👍

**Comment by Rayraegah** [comment]
oh? Let me try. 

I was playing with your example. Perhaps, its just a js thing.

```
    /**
     * @todo Add deep watch for state to prevent mutations outside handlers
     * @body [not safe for production](https://vuex.vuejs.org/en/strict.html)
     */
```
![image](https://user-images.githubusercontent.com/1559650/36517163-99eddce4-17c4-11e8-899a-fb0706d59735.png)

**Comment by JasonEtco** [comment]
Ah ok good to know @Rayraegah thanks. That should work, so I'll go ahead and open this back up. Likely just an encoding thing in the templater (tries to make sure that certain characters aren't used because they're "unsafe"). Will work that out 👍

**Comment by JasonEtco** [comment]
Oh wait; is that on the demo page? That's a totally different thing than the app itself. The app itself _should_ render markdown just fine. The demo page does not, but it could, I'd just have to add that (or you could PR 😉)

**Comment by JasonEtco** [comment]
I've gone ahead and added markdown formatting to the demo page (it was already doable in the app itself, GitHub will just render the markdown). Thanks 🎉
