### ISSUE TITLE
Code Block does not work

### ISSUE THREAD

**Issue by Rayraegah** [JasonEtco/todo#111]
Maybe it is the`.editorconfig`?

Example: https://github.com/Rayraegah/warui/issues/1
![image](https://user-images.githubusercontent.com/1559650/36586367-d5b7de2c-18c4-11e8-95d2-a54dab160452.png)

**Comment by rsarky** [comment]
If the number of lines in the file is less than 5 or something it won't show you a code block.
How many lines did the above file have?

**Comment by JasonEtco** [comment]
Thanks for the report @Rayraegah, definitely something buggy going on in there.

**Comment by rsarky** [comment]
@Rayraegah Could you attach a screenshot with the contents of the above file?

**Comment by JasonEtco** [comment]
It looks like the RegEx is matching before the part of the diff that the `todo` is in, so it picks up the first file name and line in the diff.
