### ISSUE TITLE
Add emoji to default label

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/todo#113]
GitHub Labels [now support emoji](https://twitter.com/github/status/966467599566389248) 🎉 ⭐️ ✨ 🌮 

The label that **todo** creates (<kbd>todo</kbd>) by default should have an emoji! I'd love for a first-time contributor to take this on 👍

**Comment by AshanthaLahiru** [comment]
@JasonEtco , I gave it a try, could review my pull request and let me know if there is anything?

**Comment by JasonEtco** [comment]
Closed by #117. Thanks @AshanthaLahiru ❤️
