### ISSUE TITLE
Seeing duplicate PR comments

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/todo#120]
The age-old _duplicate_ error is still happening, now noticed with PR comments. **todo** is creating duplicate comments in pull requests for the same `todo`.

**Comment by rsarky** [comment]
_duplicate_ error? :thinking: :

**Comment by JasonEtco** [comment]
One possible fix is to get the diff of the most recent commit in the PR, rather than the diff of the entire PR - that way `todo` would only run on the most recent changes, and wouldn't recreate the same comment.

**Comment by rsarky** [comment]
I can try and look into this if it's okay with you?

**Comment by unional** [comment]
I get one comment in the PR https://github.com/unional/komondor-plugin/pull/6
but two issues created: https://github.com/unional/komondor-plugin/issues

🌷

**Comment by Seluj78** [comment]
:+1: for reopening #99 

I thought i'd give a second try to probot but it's still having the same issues with PRs at least, i'll let you know as soon as I merge them

The PR I am  having trouble with: https://github.com/OpenApprenticeFoundation/openapprentice-website/pull/9

**Comment by Seluj78** [comment]
Here's a screenshot of a commit that DIDN'T add any TODOs and still made the bot add more comments

![screenshot-2018-6-12 new flask version of oa by seluj78 pull request 9 openapprenticefoundation openapprentice-website](https://user-images.githubusercontent.com/4641317/41276294-19ddf816-6e24-11e8-9b71-feb36ccfc2b5.png)

**Comment by rsarky** [comment]
So there are 2 problems here right?
- Single comment and Multiple issues
- Mutliple comment and singe issue.

Would you say the fix for them is related @JasonEtco

**Comment by JasonEtco** [comment]
@rsarky it's likely a similar cause: the code to check  if an issue or comment already exists (which is too separate code paths, that do similar things) is not working as intended.

**Comment by Divy123** [comment]
Is this issue still open?
I would like to work upon it.

**Comment by Seluj78** [comment]
Hi @Divy123, yes the issue is definitely still open ! Help yourself ;)

**Comment by JasonEtco** [comment]
This should be fixed as of #165 - if anyones still seeing it feel free to reopen. Thanks everyone!
