### ISSUE TITLE
Allow for limiting creation of issues only when merging on specific/protected branches

### ISSUE THREAD

**Issue by skleanthous** [JasonEtco/todo#128]
In our workflow, we allow for merging code into non-protected branches that is not stable. This means that there are TODO comments in there, but these will get removed prior to merging into a protected branch. 

What would be right is to allow to filter the branches on which todo bot runs.

**Comment by JasonEtco** [comment]
Hey @skleanthous 👋 

Am I understanding correctly that you want issues to be opened when a PR is merged into a branch that **is not** the default branch (in most cases `master`)? If that's the case, I am definitely on board for adding a config option for it. How about something like:

```yml
mergeBranches:
  - master
  - dev
```

**Comment by skleanthous** [comment]
Hello @JasonEtco,

Yeah, we do need to configure which branches this pluging will inspect. An explicit inclusion will work quite nicely for us. Something like what you recommend will work perfectly.

**Comment by JasonEtco** [comment]
Cool, sounds good. I won't have time to work on this for another few weeks; @skleanthous, PRs are welcome 😀

**Comment by skleanthous** [comment]
OK, I'll see what I can do :)

**Comment by samuelgeurts** [comment]
Has there been any progress on this issue?
A also have todo's on a dev branch.

**Comment by skleanthous** [comment]
@samuelgeurts Sorry, no progress from my side and I don't think there will be :|
