### ISSUE TITLE
Close issue when TODO is removed?

### ISSUE THREAD

**Issue by koddsson** [JasonEtco/todo#129]
Since we can already see duplicate issues I feel like it could be trivial to see if we are removing a TODO, find the corresponding TODO issue and close it when pushing to master. In PRs we could edit the commit body to say "Closes #[number]" so that the issues are closed when it's merged.

What do you think?

**Comment by JasonEtco** [comment]
Heck yes, I’ve wanted this for awhile, just haven’t gotten around to doing it. Right now it uses the ‘+’ character in diffs to identify new todos; we can use the inverse ‘-‘ to remove them, with the same regex (and capture group the -/+). Pull request welcome 😘 otherwise I’ll probably be able to work on it mid April.

**Comment by rsarky** [comment]
I am open to work on this @koddsson @JasonEtco 
Down with some school work for now :cry: but could start around first week of April.

**Comment by koddsson** [comment]
>Pull request welcome 😘

@JasonEtco 

Awesome! This issue was originally going to be a PR but I wasn't sure where all the pieces that I needed to do this where or if this was even possible from reading the code. Mind if I drop some lines of code in here and you can tell me if I'm right or wrong?

(*assumes answer is yes*)

Cool!

---

One thing I could not wrap my head around was this regex:

https://github.com/JasonEtco/todo/blob/f7914a00ff5146dbc93738612fbbf9f558fb7086/src/utils/chunk-diff.js#L18

Could you give me the what-what on this? From context it seems like this is the place where we find `TODO` comments that have been added and we return those diffs?

---

Here's another regex that I think is responsible for finding all the added (`+`) `TODO` items.

https://github.com/JasonEtco/todo/blob/f7914a00ff5146dbc93738612fbbf9f558fb7086/src/utils/parse-chunk.js#L24

The rest of the file parses the code around it to gather up info to post as a issue?

---

So I think I mostly need to change these files and change the regex to find removed lines as well, mark those somehow as being removed and then when detecting duplicates I can close those if there is a duplicate?

**Comment by JasonEtco** [comment]
What do you mean @koddsson, those RegExes are all so clear and understandable `/sarcasm`!

The first one, in `chunk-diff.js`, takes a whole diff and returns an array of chunks. So for example, given this:

```
diff --git a/bin/todo.js b/bin/todo.js
index bc649d0..666960b 100755
--- a/bin/todo.js
+++ b/bin/todo.js
@@ -2,7 +2,7 @@
 
 const program = require('commander')
 const chalk = require('chalk')
-const GitHubAPI = require('github')
+const octokit = require('@octokit/rest')()
diff --git a/package.json b/package.json
index 8b30cb6..8768e00 100644
--- a/package.json
+++ b/package.json
@@ -41,9 +41,9 @@
   },
   "dependencies": {
     "@google-cloud/logging-bunyan": "^0.7.0",
+    "@octokit/rest": "^15.1.7",
     "chalk": "^2.3.1",
     "commander": "^2.14.1",
-    "github": "^14.0.0",
```

It'd split it into two chunks, one for changes to `bin/todo.js` and one for changes to `package.json`. This is mostly for ease-of-handling, and to have more determinable file names and line numbers.

---

That second RegEx parses a match, so when the overarching RegEx finds a TODO in a chunk in a diff, it'll send that chunk over to `parse-chunk.js`. You'll notice at the top I define variables from the capture groups:

https://github.com/JasonEtco/todo/blob/f7914a00ff5146dbc93738612fbbf9f558fb7086/src/utils/parse-chunk.js#L10-L18

Those come from this RegEx that actually parses the chunks and captures the right stuff:
https://github.com/JasonEtco/todo/blob/f7914a00ff5146dbc93738612fbbf9f558fb7086/src/utils/handler-setup.js#L14

Somewhere in there is `^(\\+)` - that's capturing the prefix (and there's even a variable for it in `chunk-diff.js`!). I was originally planning to treat removals differently, so at one point that was actually `^([-+])`, allowing for either prefix. That's where I'd start identifying the different lines.

Happy to talk through more of this, it gets a little messy with all the RegEx, but I think that with the variable `prefix` it's already a good ways into knowing when a TODO is removed - just need to do something with that information 🙌

**Comment by koddsson** [comment]
@JasonEtco 

Awesome! I made a change here but my tests are failing because the regular expression capture group(?) isn't picking up both TODO comments in the file and I don't know enough regex to change it 😭 

Here's the PR: https://github.com/JasonEtco/todo/pull/130

I loaded the regex up on regex101.com and tried fiddling with it but I can't seem to capture both comments when the regex has `^([-+])`. Here's the link to the regex loaded in regex101: https://regex101.com/r/O5hUJr/1

Note that if I change it to be `^([-])`, the test will run green 😄

**Comment by rsarky** [comment]
> I loaded the regex up on regex101.com and tried fiddling with it but I can't seem to capture both comments when the regex has ^([-+]).

`^diff --git a\/.+ b\/(.+)[\s\S]+?^@{2}.+\+(\d+).+@{2}$([\s\S]+?(^(-|\\+).*(@todo|TODO)(?:[:-\s]+)?\s(.*))[\s\S]+)` . This captures both comments. Wonder why `[-+]` is not working though. :thinking:

**Comment by NilsDannemann** [comment]
Just wondering if there is any progress on this? Would be quite a helpful feature. <3

**Comment by JasonEtco** [comment]
@NilsDannemann I've started on an implementation in #184 - it needs some work still though. Feel free to follow along there!

**Comment by EvanLovely** [comment]
This would be super helpful to have. Re: RegEx readability - I’ve done them like this in the past and I find it helps myself and others who come back to that code later:

```js
  /* eslint-disable prettier/prettier */
  const twigRegex = new RegExp(
    "(?<=" + // begin lookahead assertion; these patterns must appear before and will not be included in result
      "(include|extends|embed) " + // any of these words and then a space
      "[\"|']" + // either `"` or `'`
    ")" + // end lookahead assertion
    "(.*\.twig)" // this will be captured as result. any character `.` infinite times `*` followed by a literal period `\.` and then `twig`
    , 'g'); // Regex flags - `g`: global
  /* eslint-enable prettier/prettier */
```
