### ISSUE TITLE
Issue is only being created for first TODO comment

### ISSUE THREAD

**Issue by aes421** [JasonEtco/todo#136]
My diff is returning as follows...

```
diff --git a/index.js b/index.js
index 8f73afc..0857b98 100644
--- a/index.js
+++ b/index.js
@@ -88,14 +88,15 @@ bot.dialog('homePrinterHead', (session)=>{
             console.log('error: '+ response.statusCode);
             console.log(body);
         }
-        //TODO Not sure if endConversation is appropriate here
+        // TODO endConversation is probably not appropriate here
         session.endConversation();
     });
 }).triggerAction({
     matches: "PrinterOperations.PrintHead.Home"
 });
 
-//TODO only possible to use relative positioning currently
+// TODO write code to make absolute positioning possible
+// BODY currently only relative positioning is possible
 bot.dialog('jogPrintHead', [
     function (session, args, next){
         session.say("moving printhead");
@@ -161,7 +162,7 @@ bot.dialog('jogPrintHead', [
                 console.log('error: '+ response.statusCode);
                 console.log(body);
             }
-            //TODO Not sure if endConversation is appropriate here
+            // TODO endConversation is probably not appropriate here
             session.endConversation();
         });
     }
@@ -180,7 +181,7 @@ bot.dialog('getStatus', (session)=>{
         }
     };
 
-    //TODO continue calling until request is done.
+    // TODO continue calling this until request is done.
     session.sendTyping();
     request(options, (error, response, body) => {
         if (error){
@@ -226,7 +227,4 @@ bot.dialog('getStatus', (session)=>{
     // });
 }).triggerAction({
     matches: "PrinterOperations.Status"
-});
-
-// TODO test1
-// @todo test3
\ No newline at end of file
+});
\ No newline at end of file
```

I would like to debug this issue, but I am unclear where to look.  In push-handler, chunkDiff is coming back with one large chunk with that entire diff in it. Then in push-handler `match = regex.exec(chunk) ` is being called and match is being set to the very first TODO statement.  It then creates one issue for that first TODO and exits the program.

**Comment by aes421** [comment]
I think I found the issue... it looks like in your tests (below) every change is starts with
```
diff --git a/file.txt b/file.txt
index 0d43cbb..4e652e9 100644
--- a/file.txt
+++ b/file.txt
@@ -4,21 +4,22 @@
```

What I am getting back from chunkDiff only has it at the very top.  Any suggestions?

```
diff --git a/file.txt b/file.txt
index 0d43cbb..4e652e9 100644
--- a/file.txt
+++ b/file.txt
@@ -4,21 +4,22 @@
+ // TODO Title number 1
diff --git a/file.txt b/file.txt
index 0d43cbb..4e652e9 100644
--- a/file.txt
+++ b/file.txt
@@ -4,21 +4,22 @@
+ // TODO Title number 2
diff --git a/file.txt b/file.txt
index 0d43cbb..4e652e9 100644
--- a/file.txt
+++ b/file.txt
@@ -4,21 +4,22 @@
+ // TODO Title number 3
diff --git a/file.txt b/file.txt
index 0d43cbb..4e652e9 100644
--- a/file.txt
+++ b/file.txt
@@ -4,21 +4,22 @@
+ // TODO Title number 4
diff --git a/file.txt b/file.txt
index 0d43cbb..4e652e9 100644
--- a/file.txt
+++ b/file.txt
@@ -4,21 +4,22 @@
+ // TODO Title number 5
```

**Comment by JasonEtco** [comment]
`chunkDiff` separates one large diff into different chunks based on their file path. For example, if a commit modifies two files, that commit will still only have one diff - `chunkDiff` "chunks" the diff into pieces that are easier to parse as separate files, which is important when putting together the new issue body that contains a filename and code blob. That said, there is still a match loop within the string that `chunkDiff` returns:

https://github.com/JasonEtco/todo/blob/b1e49533b783fe8a345bc24aad32b47d625db6d2/src/push-handler.js#L28-L32

That said, I'm not sure why its only opening the first issue. Is this something you noticed in production, or while running the CLI (or both)?

**Comment by aes421** [comment]
I see where chunkDiff splits based off file path.
If I have 1 file with multiple new TODO's, it gets split into 1 single chunk.  I assume that's right?
Should parseChunk be receiving 1 TODO as match or all the TODO's from that file?

Currently the regex in push_handler matches like this (https://regexr.com/3naf7) and sends the whole thing to parseChunk.  parseChunk then only parses the first TODO.

I am currently running it locally.

**Comment by JasonEtco** [comment]
> If I have 1 file with multiple new TODO's, it gets split into 1 single chunk. I assume that's right?

Yep thats right, each chunk represents one file. Note that this is not the same as Git's [hunk](https://www.bignerdranch.com/blog/using-git-hunks/) paradigm, which is separated by the `@@...@@` lines.

> Currently the regex in push_handler matches like this

Because the RegEx has the `g` global flag, it should be able to run repeatedly in a while loop until the `regex.exec(string)` returns `null`. `parseChunk` is called within that while loop, so it _should_ be run every time theres a match. I'll look into why it isn't doing that.

**Comment by Favna** [comment]
I can also confirm this issue. I just commited [this](https://github.com/Favna/Ribbon/commit/ac559d0e8c22559fdd5279442c6c85c2033cfcb1) to my repo and the bot only created [one issue](https://github.com/Favna/Ribbon/issues/16)

I had to make [two additional](https://github.com/Favna/Ribbon/commit/37921dfedd6a9c02bd278a2dbfa9f867cc0b6853) [commits](https://github.com/Favna/Ribbon/commit/526e0eedeb5ca64de53595e25bb7ee8103b08ebc) removing and re-adding the second todo just to get the [second issue](https://github.com/Favna/Ribbon/issues/17)

**Comment by JasonEtco** [comment]
This should be resolve after the changes in #165 - I've observed some successful output from diffs that have multiple TODOs. Thanks everyone!
