### ISSUE TITLE
Add todo bot to marketplace

### ISSUE THREAD

**Issue by maracuja-juice** [JasonEtco/todo#137]
Have you thought about submitting your bot to the [GitHub Marketplace](https://developer.github.com/apps/marketplace/)?
Biggest Requirement for that is:
`GitHub Apps should have a minimum of 250 installations.` ([here](https://developer.github.com/apps/marketplace/creating-and-submitting-your-app-for-approval/requirements-for-listing-an-app-on-github-marketplace/) are the other requirements)

**Comment by JasonEtco** [comment]
Hi @maracuja-juice 👋 

Right now the marketplace is only setup to show apps that have at least one paid option - **todo** does not and probably (definitely) never will.

When the Marketplace support fully-free apps (TBD), I'll likely do that. Thanks for the suggestion ❤️

**Comment by maracuja-juice** [comment]
Hey @JasonEtco 
Ah I didn't know that, good to know. Hope this will change in the future :)
