### ISSUE TITLE
Todobot seemingly stopped working entirely

### ISSUE THREAD

**Issue by Favna** [JasonEtco/todo#139]
I've added some todo comments to my code on multiple commits now but the bot never picks them up and creates issues anymore. Examples of these commits are [here](https://github.com/Favna/Ribbon/commit/3a5d717568cbb707e67adbbc27a895299f348c77) and [here](https://github.com/Favna/Ribbon/commit/c2fc43c98edc0106d4c7b9055b34386e9187adaa#diff-1bb06837bf46a1b2c6cd9e2a923dacc6), neither time did the bot pick them up as TODO's. 

The only thing that comes to mind is that in both of these cases the commits were queued along with other commits when I pushed them but that really shouldn't matter.

So what gives?

p.s. I know they are the same todos, it was an attempt to get the bot to trigger. I temporarily removed it [here](https://github.com/Favna/Ribbon/commit/205bc97acb42699019de66ca4f2b203714f7b839#diff-1bb06837bf46a1b2c6cd9e2a923dacc6)

**Comment by JasonEtco** [comment]
Looks like it hit some rate limiting issues. I don't have the bandwidth to solve that, but you're welcome to clone the repo and [host your own instance of the app](https://github.com/JasonEtco/todo/blob/master/docs/deploy.md).
