### ISSUE TITLE
Disable certain files/directories

### ISSUE THREAD

**Issue by OmgImAlexis** [JasonEtco/todo#146]
Add the option to disable certain files/directories from opening issues/comments.

For example in our use-case we have 2 directories which happen to contain our built files. These still include the `@TODO` comments as well as our source files which means your bot opens 3 seperate comments for the same issue.

Please see https://github.com/pymedusa/Medusa/issues/4468

**Comment by JasonEtco** [comment]
Could you please add a description to this issue? Its hard to keep context when switching between issues and PRs in different repos, and Tweets.

**Comment by OmgImAlexis** [comment]
@JasonEtco how's that?

**Comment by JasonEtco** [comment]
Cool @OmgImAlexis thanks.

I'm open to this - I'd love to have a config option that takes a RegEx, something like:

```yaml
exclude: /.*\/dist\/.*/
```

I don't currently have the bandwidth to add new features to this project, but if you'd like to open a PR I will happily work with you on it.

**Comment by OmgImAlexis** [comment]
If you could try and link me to where I should look at adding the filters that'd help a lot.

**Comment by JasonEtco** [comment]
Sure thing. There's currently a check to see if a parsed out filename is the config file; I think it'd make sense to add the check here:

https://github.com/JasonEtco/todo/blob/f59f365ec5adc3c9ee741ce2d5ffda5cbbe58524/src/pull-request-handler.js#L25

This could be rewritten to something like:

```js
if (parsed.filename === '.github/config.yml' || (config.exclude && parsed.filename.test(new RegExp(config.exclude))) {
  continue
}
```

This check currently exists in three places - the PR handler, the push handler and the PR merged handler.
