### ISSUE TITLE
Todo bot should cleanup comments after a rebase

### ISSUE THREAD

**Issue by rgbkrk** [JasonEtco/todo#166]
See https://github.com/nteract/nteract/pull/3680 for an example.

When an interactive rebase is performed, todo bot creates new issues for each instance of the original TODO entry. This is exacerbated when doing a refactor of existing code (the above linked PR was a typescript conversion).

cc @captainsafia

**Comment by JasonEtco** [comment]
Thanks for the issue @rgbkrk 🙏 

I think this is a race condition, where TODO generates a comment, but at the same time it gets another event and checks if that comment has been created - it all happens so fast that the GitHub API says no.

I have a possible solution, which is to basically delay any `GET` requests for a full second - I've done this in other application to counter replication lag, but it'd work here as well. Will try to get a fix out shortly!

**Comment by JasonEtco** [comment]
After re-reading this, I think I understand the question a little differently (though my previous response still brings up a good point). You're asking about Todo removing comments for things that don't exist after a rebase? If that's the case, its sort of a duplicate of #129, but much harder to detect if the diff isn't there in the first place.

**Comment by rgbkrk** [comment]
Yeah. I couldn't tell if it was also in instances where it was in the commits but not part of the overall diff.
