### ISSUE TITLE
BODY not included in issue

### ISSUE THREAD

**Issue by roblabla** [JasonEtco/todo#171]
It seems like the bot only found the TODO without matching the BODY.

Here's an example issue: https://github.com/roblabla42/KFS/issues/34
The commit responsible: https://github.com/roblabla42/KFS/commit/fbbea9f3f22fb6a6796e6594adcfdbe36e15eb28#diff-fe2e65576035df545f1f4f7908915e70R48
And the config: https://github.com/roblabla42/KFS/blob/master/.github/config.yml

I suppose it's a bug in the body regex?

**Comment by JasonEtco** [comment]
Thanks for those details @roblabla - much appreciated. This definitely looks like a bug, it should be picking up the body in your provided links.

Here's the diff that's being traversed: https://github.com/roblabla42/KFS/commit/fbbea9f3f22fb6a6796e6594adcfdbe36e15eb28.diff

I'll try to look into this soon!
