### ISSUE TITLE
Multi-line BODY in source

### ISSUE THREAD

**Issue by roblabla** [JasonEtco/todo#174]
It'd be nice if TODO could handle multi-line BODY, something like https://github.com/roblabla42/KFS/pull/48#issuecomment-443809742

To prevent ambiguity, maybe TODO could look for multiple continuous lines starting with BODY?

**Comment by JasonEtco** [comment]
Thanks for this suggestion. I'd be open adding support for multiple continuous lines that match the body keyword, but a couple of questions first (not saying you need to answer them, just that we need to ask 'em):

* How will we concatenate the lines? Do we keep line breaks consistent with how it is in the code, or `.join(' ')`?
* Do we require that continuous lines match the _exact_ same body keyword, or do they only need to match the RegEx (which might include multiple keywords, or be case-insensitive)?

Would you be up for starting a PR?

**Comment by roblabla** [comment]
For the first question, I don't have a strong preference. I like what the normal markdown (not GFM) does, which is to join with a space for single linebreaks, and with a \n for double linebreaks. E.G.

```
this is a
test
```

results in "this is a test", but

```
this is a

test
```

results in "this is a\ntest".

-----------

As for your second question: I think whichever is easier on the implementation works :P. I think it'd be easier to just require each line to match the RegEx. Then we can just keep running the Regex on all lines until it stops matching. 

I'll try to get a PR up.

**Comment by JasonEtco** [comment]
Great, those both sound good to me. Thanks for talking through it!

**Comment by roblabla** [comment]
I'm stuck with a bit of an odd problem:

```
BODY: Test
BODY:
BODY: Another test
```

This currently does not get matched, as the BODY *requires* spaces after the `:` to get matched. I thought I'd change the regex to make the whole right side of the `:` optional:

`.+(?<keyword>PIZZA|text):?(?:\s(?<body>.*))?`

This turns out to break one of the tests, namely "text This is a text". Example: https://regex101.com/r/A1FCUV/1

I'm not great at regex by any measure. I'm not 100% sure how this could be fixed, any idea would be appreciated.
