### ISSUE TITLE
Suggestion: increase the diff limit a bit

### ISSUE THREAD

**Issue by k1o0** [JasonEtco/todo#198]
A recent pull request of ours (https://github.com/cortex-lab/Rigbox/pull/119) went over the diff character limit.  

> JasonEtco commented [4 hours ago](https://github.com/JasonEtco/todo/issues/186#issuecomment-474832268):
> @k1o0 it appears that that PR's diff is too large: `136635/100000` (`your pr / the limit`). I instituted a limit to the size of diffs that would be parsed because overly large diffs (like people committing minified files) were causing downtime (see #194). Happy to raise that limit if needed, it was an arbitrary thing (I did some digging to find the average diff size internally).

I'm not sure what precisely counts towards the total number, for instance we did rename a few files, however these were recognized as such by Git.  This was indeed one of our larger PRs though, so this probably won't occur very often...

**Comment by JasonEtco** [comment]
Thanks for opening @k1o0 🙏 this PR doesn't look large enough that I'd consider it "bad for TODO" - so, without hard data to back it up, I would let this one through. I'm thinking we bump the limit to `150000`, and see what happens.

For your information, its the size of the diff in its entirety - so for renamed files, that'd be the contents of the file twiceover, once as `- ...` under the previous name and once as `+ ...` under the new name. This system definitely conflicts with TODO's opinion of a "large" diff, but it shouldn't be acting on renamed files anyway.

Do you want to open a PR? That'd be right here:

https://github.com/JasonEtco/todo/blob/c24bd7d1bd24b063d109cc70e4fef64613ee552b/lib/utils/get-diff.js#L1-L6
