### ISSUE TITLE
The App is not Working at all

### ISSUE THREAD

**Issue by zsubzwary** [JasonEtco/todo#200]
**Describe the bug**
Not showing up with issues !!

**To Reproduce**
1. Install with access to all repo
2. Add following 
```
todo:
    keyword: "@makeAnIssue"
``` 
to `.github/config.yml`
3. Commit with a comment containing `@todo implement this later` followed by some text

**Expected behavior**
This should open an Issue with the title _(in this case)_ **implement this later**

**Screenshots**
1. Given Permission: ![Permission](https://imgur.com/5jXqexy.jpg)
2. Added a `// @todo` to check it out ![todo](https://imgur.com/W6lQbkw.jpg)
3. Still no Issues ![No Issues](https://imgur.com/cqdClev.jpg)

**Additional context**
There aren’t any other context about the problem.

**Comment by JasonEtco** [comment]
@zsubzwary setting the keyword to `@makeAnIssue` is an optional configuration, and changes what code comment you need to check in to create new issues. This is what you would use now:

```js
/*
 * @makeAnIssue New issue!
 */
function example () {}
```

It sounds like you want the default behavior, so just remove the `config.yml` file entirely. Hope that helps!

**Comment by zsubzwary** [comment]
Thanks @JasonEtco it did solved my problem !!
# 👍
