### ISSUE TITLE
@[ ] and @[x] for adding/modifying task lists

### ISSUE THREAD

**Issue by Pawper** [JasonEtco/todo#202]
**Is your feature request related to a problem? Please describe.**
Currently task lists are supported in the following format:

```
/**
 * @todo This issue has a task list
 * @body Here's the body text  
 * @body
 * @body - [ ] Here's an unchecked task 
 * @body
 * @body - [x] This one's done  
 */
```
However this requires a lot of lines.

**Describe the solution you'd like**
I'd like it to work like this:

```
/**
 * @todo This issue has a task list
 * @body Here's the body text
 * @[ ] Here's an unchecked task
 * @[x] This one's done
 */
```

**Describe alternatives you've considered**
I thought ```<br>``` might work but it does not after a couple different attempts.
```
  * @todo This issue has a task list 
  * @body Here's the body text<br> 
  * @body - [ ] Here's a checkbox?<br> 
  * @body - [x] This one's done 
  */ 
```
also tried
```
 /**
 * @todo This issue has a task list
 * @body Here's the body text<br>- [ ] Here's a checkbox?<br>- [x] This one's done
 */
```
**Additional context**
I've been experimenting with this over at https://github.com/Pawper/Testing-Workflow

**Comment by JasonEtco** [comment]
Thanks for the details here @Pawper! This _should_ work:

>  I thought <br> might work but it does not after a couple different attempts.

What happens? Does it still just use the first line, or does it have multiple lines but the checkboxes don't render properly?

**Comment by JasonEtco** [comment]
It looks like [this one](https://github.com/Pawper/Testing-Workflow/issues/6) should have worked, but the body is rendering with spaces before the `- [ ]`, which causes it to not render the checkboxes. Here's the markdown body of the issue:

```
"Testing more for GitHub&#x27;s todo app for checkboxes<br> - [ ] Here&#x27;s a checkbox?<br> - [x] This one&#x27;s done<br> blahblah\n\n---\n\nhttps://github.com/Pawper/Testing-Workflow/blob/97ec6e9044fa9e1325ba02eeabd39f6701899b8f/test.js#L17-L22\n\n---\n\n###### This issue was generated by [todo](https://todo.jasonet.co) based on a `@todo` comment in 97ec6e9044fa9e1325ba02eeabd39f6701899b8f. It&#x27;s been assigned to @Pawper because they committed the code."
```

**Comment by Pawper** [comment]
@JasonEtco Thanks for the quick replies. Yes, the issue is that the checkboxes do not render with ```<br>```. However even if ```<br>``` worked, I feel it isn't much more elegant than the empty ```@body``` lines. Ideally there would be some sensible syntax without having to use workarounds like these. Either seamless multi-line body, e.g.:
```
/**
 * @todo This issue has a task list
 * @body Here's the body text
 * @body - [ ] Here's an unchecked task
 * @body - [x] This one's done
 */ 
```
Or the initial suggestion:
```
/**
 * @todo This issue has a task list
 * @body Here's the body text
 * @[ ] Here's an unchecked task
 * @[x] This one's done
 */
```
Thanks again, really appreciate this app in what I'm figuring is a VSCode-GitHub-Todo-Automation (VGTA?) workflow 😁

**Comment by JasonEtco** [comment]
There's some previous conversation on why the first suggestion (multi-line `@body`s) won't work: https://github.com/JasonEtco/todo/issues/93. I'm open to exploring this more to see if we can make it work though!

As for the latter - I'm really hesitant to add any special syntax. TODO operates on keywords, not any fancy AST parsing - this lets it be language agnostic. Adding syntax like `@[ ]` makes sense for parsing JSDoc comments, but won't have reliable equivalents in any other language or documentation tool.

**Comment by Pawper** [comment]
Sorry, I'm a bit of an amateur, but I'm doing my best to keep up! I do see what you mean - ```@body``` is only JSDoc and TODO supports other contexts as well. There is also the idea that task lists are part of the body of the issue.

Anyway, I can go ahead with the current functionality and I'm going to delete the comments once the task list is all checked off (which I think will close issues in a future release?), so it's not seriously problematic or anything. Maybe just more encouragement for your exploration of multi-line ```@body```s.

**Comment by JasonEtco** [comment]
👋 I'm getting around to closing some old issues, and I think this one is good to close. It was an interesting discussion, and might lend itself to a future iteration of TODO that isn't based on string matching. Thanks for the discussion!
