### ISSUE TITLE
Have the todo issue's body update with edits in future commits

### ISSUE THREAD

**Issue by Pawper** [JasonEtco/todo#203]
**Is your feature request related to a problem? Please describe.**
I would like to be able to update the body of an issue, for example to check off something in a task list. Example - 
Initial commit:
```
 [//]: # TODO Testing in markdown  
 [//]: # BODY Here's a description 
 [//]: # BODY 
 [//]: # BODY - [ ] Unchecked item 1 
 [//]: # BODY 
 [//]: # BODY - [ ] Unchecked item 2
```
Updated commit:
```
 [//]: # TODO Testing in markdown  
 [//]: # BODY Here's a description 
 [//]: # BODY 
 [//]: # BODY - [x] This is now checked 
 [//]: # BODY 
 [//]: # BODY - [ ] Unchecked item 2
 [//]: # BODY 
 [//]: # BODY - [ ] This is a new item
```

**Describe the solution you'd like**
I would like it to update the body.

**Describe alternatives you've considered**
N/A

**Additional context**
Please see this repo for tests https://github.com/Pawper/Testing-Workflow/issues

**Comment by JasonEtco** [comment]
Oooh this would be really cool. It's fairly straightforward too, we'd have to search for the issue and, if it exists, update it rather than do nothing (which we already handle). Thanks for this suggestion @Pawper ❤️ If you're up for it, a PR would be great - happy to help point you in the right direction!

**Comment by Pawper** [comment]
Haha OK. I cloned the repo, and I think I am supposed to be looking at ```check-for-body.js``` (or ```check-for-body.test.js```). But I've no idea what to do next. I'll take a closer look after work.

**Comment by Pawper** [comment]
@JasonEtco I'm sorry to say, I think it may be beyond my decade-rusty beginner JavaScript. Is this where I should be looking?
```
// Prevent duplicates
    const existingIssue = await checkForDuplicateIssue(context, title)
    if (existingIssue) {
      if (typeof existingIssue === 'string') return
      context.log(`Duplicate issue found with title [${title}]`)
      return reopenClosed({ context, config, issue: existingIssue }, { keyword, sha, filename })
    }
```
I think what I am seeing is if existingIssue is a string it returns nothing, which it would be a string if counted in search results & defined by this in ```check-for-duplicate-issue.js```:
```
  if (search.data.total_count !== 0) {
    const existingIssue = search.data.items.find(issue => issue.title === title)
    return existingIssue
  }
```
So I guess the logic would be, if it is an existing issue we need to check if the body has changed, and if it has, we need to update the body.

**Comment by JasonEtco** [comment]
No worries at all @Pawper! I was serious when I offered to help, I'm not in a rush to have this figured out so I'm all for pointing you in the right direction as your JS becomes less-rusty 😁 

You're definitely on the right track - `checkForDuplicateIssue` will return the existing issue that we care about:

https://github.com/JasonEtco/todo/blob/4f399561f4717bb87faab07a687c0ca64d8cd966/lib/utils/check-for-duplicate-issue.js#L17

It returning a string should be better commented - in one "run" of todo, as it parses a diff, it will keep track of repeat `TODO`s in an array. Upon seeing a repeated comment, `checkForDuplicateIssue` will return that soon-to-be-issue's title - telling the loop for creating issues not to create a duplicate. It's a bit of a mess of race conditions, but this ensures some reliability 😅 

We'll probably want to add functionality very similar to `reopenIfClosed` - after finding an existing issue, it says "is it closed? Should we reopen it?" - we'd want to now say "let's edit it!"

https://github.com/JasonEtco/todo/blob/4f399561f4717bb87faab07a687c0ca64d8cd966/lib/push-handler.js#L37

Probably something along the lines of this, after where we declare the `body`:

```js
if (existingIssue && existingIssue.state === 'open') {
  return editIssue({ context, issue: existingIssue, body })
}
```

And `editIssue` will do something like:

```js
async function editIssue ({ context, issue, body }) {
  return context.github.issues.update(context.repo({ number: issue.number, body }))
}
```

**Comment by Pawper** [comment]
Alright, I tried to drop that code in where you indicated - however now I'm having trouble sending a pull request, haha. I'm flying a bit blind here.

Is it because I am on the master branch in my clone of the repo? or am I supposed to target a specific branch? I'm not sure, haha. I need to do some research.

Here's my changes, in the green
![2019-03-25 (1)](https://user-images.githubusercontent.com/22269691/54963679-d73d9680-4f26-11e9-8b71-82efac01e394.png)

**Comment by Pawper** [comment]
I think the problem may be that I cloned instead of forking. I gotta eat, but I'll poke more after.

**Comment by Pawper** [comment]
There we go ! https://github.com/JasonEtco/todo/pull/204
