### ISSUE TITLE
Config: adding new todo's to project(s) / milestone

### ISSUE THREAD

**Issue by Pawper** [JasonEtco/todo#205]
**Is your feature request related to a problem? Please describe.**
I currently have to go through GitHub's UI to add the TODO issues to a project.

**Describe the solution you'd like**
I'd like to be able to define in the config file project(s) / a milestone to add the issues to.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JasonEtco** [comment]
Thank you for all the recent discussions @Pawper! ✨ Really great to talk through these things.

This one I have a quick answer to: I don't believe that this fits into todo. The goal of the app is to help people make notes for themselves quickly, in a long-term way, without losing context and getting distracted from their code. Introducing features that require thought, planning and (usually) switching over to GitHub to identify the name of the project/milestone, would hamper that experience. Plus, with workflow stuff like that, there's no end - and todo would become more and more complicated to use.

Hope that makes sense! I'm going to close this out, but I'm happy to reopen for further discussion if you'd like!
