### ISSUE TITLE
Server does not process events (just receive)

### ISSUE THREAD

**Issue by gencer** [JasonEtco/todo#208]
**Describe the bug**
Server does not process events (just receive)

**To Reproduce**
1. Run server with this:

```
APP_ID=29*** \
WEBHOOK_SECRET=*** \
NODE_ENV=production \
PRIVATE_KEY="$(cat private.pem)" \
LOG_LEVEL=debug \
PORT=3005 npm start
```

2. Edit a file, add a todo and Push.
3. Server receives event and says:

```
08:52:54.132Z  INFO http: POST / 400 - 1.12 ms (id=043b87ee-64dc-11e9-9d97-*)
08:53:24.268Z DEBUG probot: Webhook received
  event: {
    "event": "push",
    "id": "1630d620-64dc-11e9-****-****",
    "installation": *****,
    "repository": "nienbo/gitsby"
  }
08:53:24.269Z  INFO event: Received event (id=1630d620-64dc-11e9-83f5-*, owner=nienbo, repo=gitsby)
08:53:24.269Z  INFO http: POST / 200 - 2.95 ms (id=1630d620-64dc-11e9-83f5-*)
```

Thats all. No processing of event, no fetching data from repository to read and find todos. Just receives an event.

**Expected behavior**
I expect that todo download and parse my source and find the usages. But it just receives a webhook event. Nothing more.

I gave the permission mentioned at deploy.md file in `docs/` folder.

Webhook url has no `/probot` suffix. It is plain HTTP URL ends with trailing slash.

I am using internal server for `todo`. Not heroku or GCS...

**Comment by gencer** [comment]
Nope, It is working. I hit this issue: https://github.com/JasonEtco/todo/issues/128

I was pushing to another branch. It should be `master`. It would be better to have a multi-branch support.

**Comment by en1zero** [comment]
Nedir bu dostum

**Comment by JasonEtco** [comment]
Looks like there's nothing left here so I'm going to close it out.
