### ISSUE TITLE
[BUG] If merging a PR via "Rebase and Merge" TODO creates two issues

### ISSUE THREAD

**Issue by Cogitri** [JasonEtco/todo#223]
**Describe the bug**
After I merged https://github.com/Cogitri/gxi/pull/226 TODO created both https://github.com/Cogitri/gxi/issues/234 and https://github.com/Cogitri/gxi/issues/235

**To Reproduce**
1. Create a PR with triggers TODO
2. Merge it via "Rebase and Merge" (to not create a merge commit"
3. Todo creates two issues for the same TODO

**Expected behavior**
Only create one issue for this one TODO

**Comment by jeremyfrank** [comment]
I can confirm this is happening. It also happens with "Squash and merge."

**Comment by jac1013** [comment]
I can confirm this too, happened to me today.

**Comment by crowd-studio** [comment]
I can confirm this still happening with _Squash and merge_
