### ISSUE TITLE
Add support for Markdown to docs

### ISSUE THREAD

**Issue by Umbyology** [JasonEtco/todo#227]
FYI ... Thought you could add this information to the instruction for ToDo ...

Adding HTML or other code does not play well with Markdown as the comments show in the generated output for most Markdown editors.

However, the following syntax can be used as most Markdown editors will ignore it and the comments won’t appear in the generated output. Very useful for creating documents using GitHub Markdown while having comments in the work.

```
[//]: # @todo This syntax works like a comment, and won't appear in any output.
[//]: # @body It’s a little bizarre, but it works with many Markdown editor including Pandoc.
```

I've tested it, works perfectly.

Thanks for this great GitHub App!

**Comment by JasonEtco** [comment]
Hiya! This is neat, as I understand this is more of a notice that something _is_ working than a bug right? If you're interested in opening a PR for some doc improvements that'd be awesome. Thanks for sharing!

**Comment by JasonEtco** [comment]
I'm going to close this because of a lack of activity. If anyone wants to pick this up, feel free to comment and we can reopen!
