### ISSUE TITLE
[BUG] now.sh has some problems

### ISSUE THREAD

**Issue by cyberhck** [JasonEtco/todo#230]
**Describe the bug**
https://todo-github-app.now.sh/ping has 503 error

**To Reproduce**
1. Go to 'https://todo-github-app.now.sh/ping'

**Expected behavior**
response 200 with text "PONG"

**Screenshots**

**Additional context**

I'm blocked by this behavior because https://github.com/probot/probot.github.io/blob/master/_apps/todo.md fails on CI, please either fix it or remove todo from master branch there :)

**Comment by JasonEtco** [comment]
This has been updated. Also, this was not the correct repo to open an issue in. Please keep that in mind next time :)

**Comment by cyberhck** [comment]
what do you mean this wasn't the correct repo, your deployment isn't working, to this time, it's still 503, 
![image](https://user-images.githubusercontent.com/3640284/65816483-45407e80-e226-11e9-8699-1d9ab8645aae.png)

that's your repo, isn't it?

**Comment by JasonEtco** [comment]
That's not where its deployed anymore.

**Comment by cyberhck** [comment]
well, the way I came here was by looking at probot.github.io's todo.md file, it mentioned the now.sh url which wasn't working resulting builds to fail, so I simply create a issue to author of that app, how's that not correct repo?

I understand that it's fixed now, and it's moved to heroku.
