### ISSUE TITLE
[BUG] TODOs as comments not converted to issues

### ISSUE THREAD

**Issue by doctorperceptron** [JasonEtco/todo#233]
TODOs don't seem to get created as issues anymore after merging to master. 

In my most recent pull request the TODO I added in my branch of the code was correctly pulled out as a comment by the bot, but after merging to master no new issue was created.

**Comment by doctorperceptron** [comment]
Possibly notable, the branch in question was subsequently merged into another feature branch that has an open PR, before the current PR was closed. Connected?

**Comment by JasonEtco** [comment]
Hey @doctorperceptron :wave: If I understand correctly, that's expected behavior. TODO doesn't care about _merge commits_, only about _merged PRs_. Does that line up with what happened for you? If not, can you point me to the PR in question?

**Comment by doctorperceptron** [comment]
Hi @JasonEtco . No it was a merged PR. Private company repo unfortunately so I can't share. Will do some testing this weekend and see if I can consistently reproduce the behaviour.

**Comment by JasonEtco** [comment]
Cool, thanks for the investigation @doctorperceptron!

**Comment by doctorperceptron** [comment]
I'm having a hard time reproducing this and things seem to be working again, so closing this issue.
