### ISSUE TITLE
Add support for converting TODO file to issues

### ISSUE THREAD

**Issue by tjysdsg** [JasonEtco/todo#235]
**Is your feature request related to a problem? Please describe.**
I think that many can agree that very often developers use TODO.* file to store some general TODOs as well as write TODOs in the source files. 
For example, my `TODO.md` has the content of following:
```
- I AM A ROBOT
    - ROBOT BODY
- I'LL TAKE OVER THE EARTH FROM WEAK HUMAN
    - ROBOT TAKE OVER THE WORLD OH YEAH
- I AM STRONGER THAN HUMAN
```
It'd be really great if `todo` automatically converts it in the TODO file to an issue.

**Describe the solution you'd like**

The ideal solution needs some extra configuration parsing. It is to simply let user specify different sets of configurations for certain files. In my case, I want to specify prefixes `- ` as a title, and `<tab>- ` as the body of an issue. IMHO, this is easy to implement using regex, just that the extra configurations might be too verbose.

**Comment by JasonEtco** [comment]
Hey @tjysdsg 👋 This is a great idea, but I don't think it fits within the scope of this app. I'd suggest making your own app, or even a GitHub Action, that accomplishes what you're describing!
