### ISSUE TITLE
Try `search` API to replace fetching all issues

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/todo#24]
TIL that the search API can actually [scope searches to issue titles or bodies](https://help.github.com/articles/searching-issues-and-pull-requests/#search-issues-or-pull-requests). So a query like this:

```
Example title in:title repo:JasonEtco/example

https://api.github.com/search/issues?q=Example%20title+in:title+repo:JasonEtco/example
```

Will only look for issues with the title of "Take over the entire world" in the given repo.

**Note:** For some reason, `in:body` doesn't seem to pick up on HTML comments used by [`metadata`](https://github.com/probot/metadata). That's a real shame 😭

**Comment by bkeepers** [comment]
> Note: For some reason, in:body doesn't seem to pick up on HTML comments used by metadata. That's a real shame 😭

It would be _so_ awesome if we could figure out a way to have searchable metadata.

**Comment by JasonEtco** [comment]
Agreed @bkeepers - unfortunately, it just doesn't work. I'm guessing its intentional to not search HTML comments; they must parse it has HTML instead of text? I'm not sure. But my testing has made it very clear that the HTML comments is really the blocker. I think its a good question for folks at GH.

**Comment by JasonEtco** [comment]
For example, this should show _something_: https://github.com/search?q=%3C%21--+in%3Abody&type=Issues&utf8=%E2%9C%93 but there are 0 search results.

**Comment by JasonEtco** [comment]
Closing this because I've implemented the search API, but @bkeepers we should still be on the lookout/bugging GH to see if searching body metadata (HTML comments) will ever be a thing cuz it'd be dope.
