### ISSUE TITLE
[BUG] Issues not being created with symbols in custom keywords

### ISSUE THREAD

**Issue by C-Fergus** [JasonEtco/todo#245]
**Describe the bug**
When you use custom keywords, including the following code which is provided in the [Configuring for your project](https://github.com/JasonEtco/todo#configuring-for-your-project) section of the readme, issues are not created:

`todo:
  keyword: "@makeAnIssue"`

**To Reproduce**
1. Create a `.github/config.yml` file with a custom keyword such as `@makeAnIssue`.
2. Attempt to create an issue by pushing code using the keyword.

**Expected behavior**
A new issue should be created upon pushing

**Comment by JasonEtco** [comment]
Thanks for opening @C-Fergus 🙏 the change in #242 caused issues with keywords that have a preceding `@`; if you remove that you'll be able to use a custom keyword. There's a test that confirms this behavior:

https://github.com/JasonEtco/todo/blob/b4bf28cea7191b4f6094c4da6b7ba8f05554cbba/tests/push-handler.test.js#L125-L130

That said, the docs need updating. If you're up for a PR that'd be great!

**Comment by C-Fergus** [comment]
I think the issue may be with using any symbol before any text as "/" also does not work (maybe you can't use symbols at all?). I'm up for a pull request, would it be for updating the documentation or for changing the usage to accept symbols?

**Comment by tripptuttle** [comment]
Heya folks, confirming I'm seeing the same issue. I also just deleted the entire todo.yml config and still not getting issues with @todo or TODO
