### ISSUE TITLE
[BUG] Can't exclude all files

### ISSUE THREAD

**Issue by potibas** [JasonEtco/todo#248]
**Describe the bug**
The `exclude` option doesn't seem to be working to exclude all files.

**To Reproduce**
Add a `.github/config.yml` file to your repo containing:

```yaml
todo:
  exclude: .*
```

(I also tried to wrap in quotes: `".*"`, with no success)

**Expected behavior**
No comments or issues should be created by the todo bot.

**Additional context**
I know it's rather strange to exclude *all* files from the bot, but this comes from the fact that I cannot disable the todo bot entirely on my repository (it's enabled company-wise by default, and there's no way to configure an _exclusion_ on github, only _inclusions_).

We have a lot of documentation where the portuguese word "método" occurs, and the wrong todo comments diverts attention a lot.

**Comment by JasonEtco** [comment]
Hey @potibas 👋 this is definitely not something I'd considered 😅 my first inclination would be to not install it on all repos, and instead to be more selective. That said, the above should work. Alternatively, you can change the custom keyword to something obscure, so that it doesn't trigger on `método`.

**Comment by potibas** [comment]
Didn't know about that one, thanks.

However it still doesn't work even after changing the keyword to "thingamagingamabob". I probably have some misconfiguration somewhere, it seems it's just ignoring the `.github/config.yml` file.

Anyway thanks for your help.

**Comment by potibas** [comment]
I'm closing this, it doesn't seem to be a bug with the bot, probably some weird configuration problem on my end. Again thanks!
