### ISSUE TITLE
[BUG] Issues not created with @todo

### ISSUE THREAD

**Issue by DustRaven** [JasonEtco/todo#254]
**Describe the bug**
I added @todo comments in my code like the instructions said, but no issues are created. If i use //TODO it works as intended.

**To Reproduce**
1. Create a block comment containing @todo
2. Commit and push to master

**Expected behavior**
An issue should be created.

**Additional context**
I'm using Rider (C# IDE by Jetbrains) and the GitHub plugin.
The repo can be found `[here](https://github.com/DustRaven/Listard)`

**Comment by NakorTBR** [comment]
I'm having the same problem in a Dart project. Writing a TODO comment does not create an issue.  I did like 12 pushes trying different things to find out how to get it to work.

I'm using Android Studio if that matters.

`// TODO: Fill out card.
// @todo Fill out card
// todo Fill out card
/* @todo Fill out card */`

Nothing seems to work.

**Comment by FakeSend** [comment]
Same, I found out that it only dont works when I push via Gitkraken or git in generell, if you do the commit via the website it works only.

**Comment by frou** [comment]
I've seen todos not being created. IIRC each time it happened, my commit adding the todo was not the most recent commit at the time I pushed to GitHub.

**Comment by davizzx** [comment]
Same struggling here, I never got it working but today I pushed "Todo" in a template (not in a comment) and it triggered. Pushed from VSC and tried pushing again in the same file but didn't get it to work again

**Comment by ImJustToNy** [comment]
Same problem, it rarely creates todos, despite it worked without any problems whatsoever few weeks ago.

**Comment by frou** [comment]
🐷

**Comment by carmelly** [comment]
Same problem here, I just installed and pushed a @todo and the app simply isn't doing anything.

**Comment by ratnanil** [comment]
`//todo` works for me where as `@todo `stopped working yesterday (it did initially work)

**Comment by webberwang** [comment]
`@todo` stopped working as well

**Comment by ImJustToNy** [comment]
Bump
