### ISSUE TITLE
[BUG] Duplicated comments

### ISSUE THREAD

**Issue by sergeh** [JasonEtco/todo#256]
**Describe the bug**
Comments are being duplicated when multiple commits are pushed to a pull request

**To Reproduce**
1. Open a PR with a todo in a commit
2. Push a commit with an update that doesn't touch the same file
3. See duplicate comments

**Expected behavior**
If a todo was picked up in a pull request it shouldn't be picked up again

**Screenshots**
<img width="816" alt="image" src="https://user-images.githubusercontent.com/80928/78385879-98670580-75aa-11ea-81c2-8da6dd1a56b9.png">

**Comment by daviddesousa** [comment]
Yes

**Comment by faustomilletari** [comment]
experiencing the same issue

**Comment by flipace** [comment]
i think this is still relevant - we also experience this but it seems odd, this did work properly before :think
