### ISSUE TITLE
Can you make it work for .net 

### ISSUE THREAD

**Issue by tydinand** [JasonEtco/todo#264]
Hello Jason,
As .net core developer, I like to use your solution.
But @todo or any other @ use won't work as in mvc and razorpage this is the start character for using the model in HTML or javascript code.

Can you make that configurable to a different sign?

Thank you

**Comment by JasonEtco** [comment]
Hello 👋 You can configure a custom keyword, or you can omit the `@`. This should work just fine:

```c#
// TODO: Do some stuff.
```
