### ISSUE TITLE
[BUG] Files inside .github maybe ignored

### ISSUE THREAD

**Issue by AdityaGupta150** [JasonEtco/todo#270]
**Describe the bug**
I had this .github/config.yml, and it pointed as an issue in the repo... Maybe .github files, or just the config.yml can be ignored since it's not very likely for a repo owner to have todos in workflows files
```
todo:

  keyword: "TODO"

  keyword: "@FUTURE"
```

**To Reproduce**
1. Put TODO like above in config.yaml

**Screenshots**
![Screenshot (21)](https://user-images.githubusercontent.com/37269665/89570008-2dbd2380-d843-11ea-987b-5df4752ddb41.png)

**Not much desired, just to point out, since this isn't actually problem that will bother _much_**.

**Comment by JasonEtco** [comment]
👋 your config file isn't valid YAML, I'd recommend [trying it in a YAML validator](http://www.yamllint.com/). You can't have multiple keys of the same name (you have two `keyword` properties).
