### ISSUE TITLE
[BUG] Too many false positives

### ISSUE THREAD

**Issue by Josee9988** [JasonEtco/todo#286]
**Describe the bug**
If the .config.yml file is not described and so the bot is acting with its default rules it will create an issue for every todo word found, even though this `todo` might be inside a word.

Example:
I got multiple issues because I wrote multiple times `método` which is a word in Spain translated to (method)l

**Expected behaviour**
If I didn't set the config and I'm using the default settings I am expecting the bot to detect as an issue any `@todo` or maybe the word itself checking if it has spaces around it, but not detecting a part of a word.

Thanks!

**Comment by Josee9988** [comment]
I mean, it created over 12 issues just from 320 lines of me writing in Spanish and mentioning multiple times words like `método`(method) or `todos`(everyone). I was expecting it to only create issues if the `todo` word is surrounded by spaces or preceded by the `@` character.

**Comment by flyingcakes85** [comment]
If the word "todo" comes up often in your language, you can change the trigger keyword. Add the following to your `.github/config.yml` file.

```yml
todo:
  keyword: "@makeAnIssue"
```
