### ISSUE TITLE
[BUG] it looks like is not detecting TODO comments anymore

### ISSUE THREAD

**Issue by Raffaello** [JasonEtco/todo#294]
**Describe the bug**
when creating a comment with `// @todo ...` no comments are posted in the PR and neither issues will be created when merged.

**To Reproduce**
1. just try to do a todo comment on a PR

**Expected behavior**
It should create a TODO PR comment when a TODO comment is written.

**Screenshots**
I

**Additional context**
please have a look at this PR and commits:
https://github.com/Raffaello/threedangles/pull/11/commits/7fc68de80f7e2fb8d5008aef6f540bf79a0f34aa

No comments have been posted on the PR.

It also looks like it has been recently broken like the bot is down to process github events. is it the case?

**Comment by JasonEtco** [comment]
👋 TODO's deployment is effectively shut down - see https://github.com/JasonEtco/todo/discussions/293 for more information. I'm sorry this comes as a reactionary surprised, but unfortunately there's no way for me to notify all users of the app.
