### ISSUE TITLE
Python comments aren't supported

### ISSUE THREAD

**Issue by Seluj78** [JasonEtco/todo#88]
Hi there ! Just installed you bot and it works perfectly on C code (https://github.com/Seluj78/libft/issues/2)

But not at all on python (see https://github.com/Seluj78/IntraPy/issues and https://github.com/Seluj78/IntraPy/commit/4327c86fafdaaff7027f0ad44de26af8ef61093f)

Any fix ?

**Comment by Seluj78** [comment]
Little update, works with `#` comments, but not with 

```python
"""
Those kind of comments
"""
```

**Comment by JasonEtco** [comment]
@Seluj78 any kind of comment (multi-line, single-line) should work, as long as the comment is prefixed with your keyword (`@todo` or `TODO:` by default)

**Comment by Seluj78** [comment]
Well it's weird because python multilinear comments and bash comments didn't work for me 🤔

**Comment by Seluj78** [comment]
As I said on the other issue, the links I provided should normally show you how I layed out the comments and it didn't worked. In a later commit, I changed the python comments from `"""` to `#` and it worked

Tho it doesn't on bash script

**Comment by Seluj78** [comment]
Merged into #89
