### ISSUE TITLE
Deployment issue: todo bot misses some code

### ISSUE THREAD

**Issue by Seluj78** [JasonEtco/todo#89]
I didn't get the bot to work with bash script like this one : https://github.com/Seluj78/IntraPy/blob/master/scripts/update.sh 

Anything wrong in my comment format ?

Same for python, though this time, `#` works and `"""` doesn't

**Comment by JasonEtco** [comment]
Nothing wrong that I can see. Its file language agnostic, **todo** only cares that its text, so any language should work the same way. Did you push this file to master?

**Comment by Seluj78** [comment]
I did, the link I provided sends you to the latest version of the file and it has the comments formatted for **todo** on it. Which is why it's weird, it looks like it would be related to my other issue, #88

**Comment by JasonEtco** [comment]
@Seluj78 can you tell me the commit hash that _should_ have worked? It'll help me search through the logs.

**Comment by Seluj78** [comment]
For the python comment style, it should have been 4327c86fafdaaff7027f0ad44de26af8ef61093f (https://github.com/Seluj78/IntraPy/commit/4327c86fafdaaff7027f0ad44de26af8ef61093f) on this commit, I used the `"""` form of python comments, which sadly didn't work

Then I did https://github.com/Seluj78/IntraPy/commit/a984fcc18963144e60926a095287104e306a92c7 which worked (using `#` python comments)

Finally, after seeing that `#` worked, i changed all of them, including the bash ones.
https://github.com/Seluj78/IntraPy/commit/3e5c0416133b9748309e87478272740a3be56def this one should've worked entirely, and it almost did. The python ones worked (like earlier, with `#` but none of the bash issues were created (using `#` too)

Sorry for the lack of more formatting, I'm on my phone right now

**Comment by JasonEtco** [comment]
Cool, thanks for the info @Seluj78!

I put [this file](https://raw.githubusercontent.com/Seluj78/IntraPy/master/scripts/update.sh) through the testing suite. It generated five issues, one for each of the 5 times the keyword (`@todo`) was used. So its not Bash or Python thats the problem, it's likely a deployment thing. I'll try to find the relevant webhook payloads, but the process of finding those logs is really difficult.

**Comment by Seluj78** [comment]
Weird then 🤔 would you like to get on discord/whatever voice chat you'd like in about an hour when I get home so we can test this live ? I'm thinking about you watching the logs (can't do it myself sadly 😂) and I'll push some code containing a `@todo` to my repository and we might be able to catch the error like so

**Comment by Seluj78** [comment]
Unless you have another way/idea about doing it, just let me know @JasonEtco

**Comment by JasonEtco** [comment]
>  would you like to get on discord/whatever voice chat you'd like in about an hour when I get home so we can test this live ?

Happy to at some point, can't today though ☹️ 

I was able to find the webhook payload `062b580a-faba-11e7-9bd3-0651f3cebcb1` for that last commit (`3e5c041`). I'll try it out locally and see what happens!

**Comment by Seluj78** [comment]
Sure thing ! Let me know ! :ok-hand:

Great !

**Comment by Seluj78** [comment]
Okay yeah it definitely is a deployement thin 🤔 Take a look at [this commit which removes the todos](https://github.com/Seluj78/IntraPy/commit/cd794d2ac5a9a71d24f9fbe91a682dfca31ea505) and then [this one which adds them back](https://github.com/Seluj78/IntraPy/commit/8a48ea7392ceebd749653d9301c5888d1727182e) and now it worked ! I'll try with python multi line comments now (`"""`)

**Comment by JasonEtco** [comment]
@Seluj78 thanks for investigating! That's super odd 🤔

**Comment by Seluj78** [comment]
Alright, I'll now close all the issues created by **todo* and try again

**Comment by Seluj78** [comment]
Update, I just closed the 6 issues in `args.py`. [I commited and pushed the code](https://github.com/Seluj78/IntraPy/commit/2075b17ef5bd07c4597ceda93a852207c3b855d6) and the issues are back, so **IT IS DEFINETELY** a deployment error.

See https://github.com/Seluj78/IntraPy/issues/20 for an example of the issue re-opening

**Comment by JasonEtco** [comment]
Very strange. I'll try using the specific payload locally to see what happens and I'll let you know what I find out 👍

**Comment by Seluj78** [comment]
Sure thing ! Let me know if you need anything 👌

**Comment by Seluj78** [comment]
It struck again ! The commit https://github.com/Seluj78/IntraPy/commit/386fcea068231d57ea79da4ff8f386ecc0cb40ce created the issue https://github.com/Seluj78/IntraPy/issues/27 but none for the two other todos that were laying in the commit

**Comment by Seluj78** [comment]
Confirmed the deployment issues, I deleted the todos (https://github.com/Seluj78/IntraPy/commit/9f5a2f336d906c99300181c3960563cba5e494e8) then added them back (https://github.com/Seluj78/IntraPy/commit/eae71cd762d8bccd285035d21a8cd5141debfe85) and the two issues were created:

https://github.com/Seluj78/IntraPy/issues/28
https://github.com/Seluj78/IntraPy/issues/29

**Comment by Seluj78** [comment]
Is it deployed yet ? :)

**Comment by JasonEtco** [comment]
> Is it deployed yet ? :)

Yep 😁

**Comment by Seluj78** [comment]
Wonderful ! I'll try and let you know asap if I found any new issues
