### ISSUE TITLE
todo bot creates duplicate issues

### ISSUE THREAD

**Issue by Seluj78** [JasonEtco/todo#99]
Your bot just created duplicate issues 🤔 

https://github.com/Seluj78/42PyChecker/issues/21
https://github.com/Seluj78/42PyChecker/issues/23

https://github.com/Seluj78/42PyChecker/issues/22
https://github.com/Seluj78/42PyChecker/issues/24

**Comment by Seluj78** [comment]
so it actually looks like the bots created duplicates when `:` is placed in front of a `@todo`

**Comment by Seluj78** [comment]
Actually no
It started again without me modifying the todo lines :

http://prntscr.com/ickt9e

for example https://github.com/Seluj78/42PyChecker/issues/35 and https://github.com/Seluj78/42PyChecker/issues/39

**Comment by Seluj78** [comment]
This needs to be fixed urgently if possible :( It's spamming me of useless issues and notifications

**Comment by JasonEtco** [comment]
> This needs to be fixed urgently if possible

I know this is a bad answer, but I can't fix this right now. If you'd like to open a PR to fix it, I'm happy to merge it if it works, but I can't spend time on this right now.

**Comment by Seluj78** [comment]
😭 alright I'll see what I can do but I can't promise anything

**Comment by JasonEtco** [comment]
This might be fixed by #100. I've deployed it, let me know if you're still experiencing this issue.

**Comment by Seluj78** [comment]
I'll try and let you know asap !

**Comment by Seluj78** [comment]
Nope that didn't fix it :(

See commit https://github.com/Seluj78/42PyChecker/commit/4073465a06b03bfe2d1d2a1ebcf3909f34e5a2b6#diff-3691a24bb646b33ee279505f96ee4e60R91

and issues https://github.com/Seluj78/42PyChecker/issues/79 and https://github.com/Seluj78/42PyChecker/issues/81
